name = "WebIO"
uuid = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
license = "MIT"
version = "0.8.15"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
AssetRegistry = "bf4720bc-e11a-5d0c-854e-bdca1663c893"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Widgets = "cc8bc4a8-27d6-5769-a93b-9d913e69aa62"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"
FunctionalCollections = "de31a74c-ac4f-5751-b3fd-e18cd04993ca"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[extras]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSExpr = "97c1335a-c9c5-57fe-bc5d-ec35cebe8660"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Mux = "a975b10e-0019-58db-a62f-e48ff68538c9"
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"

[compat]
Widgets = "0.6.2"
julia = "0.7, 1"
JSExpr = "0.5"
JSON = "0.18, 0.19, 0.20, 0.21"
Observables = "0.4"
FunctionalCollections = "0.5.0"
AssetRegistry = "0.1.0"
WebSockets = "1.5.0"
Requires = "0.4.4, 0.5, 1.0.0"

[targets]
test = ["Blink", "Conda", "DataStructures", "Dates", "IJulia", "JSExpr", "Mux", "NBInclude", "NodeJS", "Test"]
